// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQmei3j-sbKLMfeAG8SNaQ4Y13VHIoIqg',
    appId: '1:355893424846:web:61e482f00f074d9e24969f',
    messagingSenderId: '355893424846',
    projectId: 'oshi-chokin',
    authDomain: 'oshi-chokin.firebaseapp.com',
    storageBucket: 'oshi-chokin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNXlIQufrTU7mxHI914_Ta-lepqvVY5ls',
    appId: '1:355893424846:android:238a804ac4ab92a024969f',
    messagingSenderId: '355893424846',
    projectId: 'oshi-chokin',
    storageBucket: 'oshi-chokin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUpD3_egKzyuHy6kA_DdBCToDBJPYXhLs',
    appId: '1:355893424846:ios:dff60deb4ac2b72a24969f',
    messagingSenderId: '355893424846',
    projectId: 'oshi-chokin',
    storageBucket: 'oshi-chokin.appspot.com',
    iosClientId: '355893424846-i6v24suj3dba8rjbi110iamjac0g9n99.apps.googleusercontent.com',
    iosBundleId: 'com.example.oshichokinFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUpD3_egKzyuHy6kA_DdBCToDBJPYXhLs',
    appId: '1:355893424846:ios:dff60deb4ac2b72a24969f',
    messagingSenderId: '355893424846',
    projectId: 'oshi-chokin',
    storageBucket: 'oshi-chokin.appspot.com',
    iosClientId: '355893424846-i6v24suj3dba8rjbi110iamjac0g9n99.apps.googleusercontent.com',
    iosBundleId: 'com.example.oshichokinFront',
  );
}
